services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"  # Mapeando a porta 8000
    networks:
      - app_network
    environment:
      - HOST=0.0.0.0  # Garantir que o FastAPI esteja ouvindo no host correto

  ollama:
    image: ollama/ollama
    volumes:
      - ./ollama-models:/root/.ollama
    ports:
      - 11434:11434
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
